using FellowOakDicom;
using FellowOakDicom.Network;
using FellowOakDicom.Network.Client;
using StorescpTool.Application.Contracts;
using StorescpTool.Core.Models;

namespace StorescpTool.Infrastructure.Dicom;

public sealed class DicomStoreTestService : IDicomStoreTestService
{
    public async Task<NetworkTestResult> SendSampleStoreAsync(
        string host,
        int port,
        string callingAe,
        string calledAe,
        CancellationToken cancellationToken = default)
    {
        var watch = System.Diagnostics.Stopwatch.StartNew();

        try
        {
            DicomCStoreResponse? response = null;
            var client = DicomClientFactory.Create(host, port, false, callingAe, calledAe);
            var file = BuildSampleFile(callingAe);
            var request = new DicomCStoreRequest(file)
            {
                OnResponseReceived = (_, received) => response = received
            };

            await client.AddRequestAsync(request);
            await client.SendAsync(cancellationToken);
            watch.Stop();

            return new NetworkTestResult
            {
                Success = response?.Status == DicomStatus.Success,
                TestType = "C-STORE SelfTest",
                Target = $"{host}:{port}",
                DurationMs = watch.ElapsedMilliseconds,
                Message = response is null
                    ? "No response from remote StoreSCP"
                    : $"C-STORE response: {response.Status}"
            };
        }
        catch (Exception ex)
        {
            watch.Stop();
            return new NetworkTestResult
            {
                Success = false,
                TestType = "C-STORE SelfTest",
                Target = $"{host}:{port}",
                DurationMs = watch.ElapsedMilliseconds,
                Message = $"C-STORE self test failed: {ex.Message}"
            };
        }
    }

    private static DicomFile BuildSampleFile(string sourceAe)
    {
        var sopInstanceUid = DicomUIDGenerator.GenerateDerivedFromUUID();
        var studyUid = DicomUIDGenerator.GenerateDerivedFromUUID();
        var seriesUid = DicomUIDGenerator.GenerateDerivedFromUUID();

        var dataset = new DicomDataset(DicomTransferSyntax.ExplicitVRLittleEndian)
        {
            { DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage },
            { DicomTag.SOPInstanceUID, sopInstanceUid },
            { DicomTag.PatientName, "STORE^SELFTEST" },
            { DicomTag.PatientID, "SELFTEST001" },
            { DicomTag.StudyInstanceUID, studyUid },
            { DicomTag.SeriesInstanceUID, seriesUid },
            { DicomTag.StudyDate, DateTime.Now },
            { DicomTag.StudyTime, DateTime.Now },
            { DicomTag.Modality, "OT" },
            { DicomTag.StudyDescription, "Local Store Self Test" },
            { DicomTag.SeriesDescription, "Generated by StorescpTool" },
            { DicomTag.Rows, (ushort)2 },
            { DicomTag.Columns, (ushort)2 },
            { DicomTag.SamplesPerPixel, (ushort)1 },
            { DicomTag.PhotometricInterpretation, "MONOCHROME2" },
            { DicomTag.BitsAllocated, (ushort)8 },
            { DicomTag.BitsStored, (ushort)8 },
            { DicomTag.HighBit, (ushort)7 },
            { DicomTag.PixelRepresentation, (ushort)0 },
            { DicomTag.PixelData, new byte[] { 0, 85, 170, 255 } }
        };

        var file = new DicomFile(dataset);
        file.FileMetaInfo.MediaStorageSOPClassUID = DicomUID.SecondaryCaptureImageStorage;
        file.FileMetaInfo.MediaStorageSOPInstanceUID = sopInstanceUid;
        file.FileMetaInfo.TransferSyntax = DicomTransferSyntax.ExplicitVRLittleEndian;
        file.FileMetaInfo.SourceApplicationEntityTitle = sourceAe;
        return file;
    }
}
